
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - deletecollection
  - list
- apiGroups:
  - restarter.tran-scending.net
  resources:
  - vaultrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - restarter.tran-scending.net
  resources:
  - vaultrestarts/status
  verbs:
  - get
  - patch
  - update
